<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "color_extractor"
 *
 * Auto generated by Extension Builder 2017-09-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ColorExtractor',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 'typo3@blue-side.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
